const fs = require("fs");
const path = require("path");

const migrationData = JSON.parse(
  fs.readFileSync(path.join(__dirname, "../migration-data.json"), "utf8"),
);

// 1. Copy files
console.log("Copying files...");
for (const item of migrationData) {
  if (item.status === "MIGRATED") {
    const oldPathFull = path.join(__dirname, "..", item.oldPath);
    const newPathFull = path.join(__dirname, "..", item.newPath);

    if (fs.existsSync(oldPathFull)) {
      const dir = path.dirname(newPathFull);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      fs.copyFileSync(oldPathFull, newPathFull);
    }
  }
}

// 2. Generate asset-manifest.ts
console.log("Generating asset-manifest.ts...");
const manifestStr = `
// AUTOGENERATED ASSET MANIFEST
// Do not hardcode /media paths directly in components. Use this manifest.

export const assets = {
  home: {
    hero: {
      desktop: "/media/images/home/hero/hero-03-desktop.png",
      mobile: "/media/images/home/hero/hero-03-mobile.png",
    },
    editorial: Array.from({ length: 14 }).map((_, i) => ({
      id: i + 1,
      desktop: \`/media/images/home/editorial/iconic-\${(i + 1).toString().padStart(2, '0')}-desktop.png\`,
      mobile: \`/media/images/home/editorial/iconic-\${(i + 1).toString().padStart(2, '0')}-mobile.png\`,
    })),
  },
  
  about: {
    teamPhoto: "/media/images/about/team-photo.jpg",
    person: "/media/images/about/person.jpg",
  },
  
  crew: {
    group: "/media/images/crew/group.png",
    getMemberPhoto: (id: number) => \`/media/images/crew/pic\${id}.jpg\`,
    getSpecialImage: (id: number) => \`/media/images/crew/special-image-0\${id}.jpg\`,
  },
  
  recentWork: {
    recent01: "/media/images/recent-work/recent01.webp",
    recent01Jpg: "/media/images/recent-work/recent01.jpg",
    recent02: "/media/images/recent-work/recent02.webp",
    recent02Png: "/media/images/recent-work/recent02.png",
    recent03: "/media/images/recent-work/recent03.webp",
    recent03Jpg: "/media/images/recent-work/recent03.jpg",
  },
  
  misc: {
    favicon: "/media/images/misc/favicon-icon.png",
    parallaxBg: "/media/images/misc/parallax-bg.jpg",
    image4: "/media/images/misc/4.webp",
    image5: "/media/images/misc/5.webp",
    image6: "/media/images/misc/6.webp",
    dscf0463: "/media/images/misc/dscf0463-copy.webp",
    redTelephone: "/media/images/misc/red-rotary-telephone.jpg",
    speakerLogo: "/media/images/misc/logo.png",
  },
  
  videos: {
    hero: "/media/videos/hero/herovideo.mp4",
    showcase: "/media/videos/showcase/the-swayamvar-2.mp4",
    background: {
      wedding: "/media/videos/background/wedding.mp4",
      celebration: "/media/videos/background/celebration.mp4",
      portraits: "/media/videos/background/portraits.mp4",
      prewedding: "/media/videos/background/prewedding.mp4",
      rituals: "/media/videos/background/rituals.mp4",
      videoseen: "/media/videos/background/videoseen.mp4",
      ivorySeries: "/media/videos/background/ivory-series.mp4",
    },
    films: {
      film01: "/media/videos/films/film-01.mp4",
      film03: "/media/videos/films/film-03.mp4",
      film05: "/media/videos/films/film-05.mp4",
      film06: "/media/videos/films/film-06.mp4",
      film07: "/media/videos/films/film-07.mp4",
      film08: "/media/videos/films/film-08.mp4",
      film09: "/media/videos/films/film-09.mp4",
    }
  },
  
  svg: {
    logo: "/media/svg/logo/swamyvar-logo.svg",
  },
  
  audio: {
    music: {
      cinematicWedding: "/media/audio/music/cinematic-wedding.mp3",
    }
  },
  
  fonts: {
    orangeAvenue: "/media/fonts/orangeavenuedemo-regular.otf",
  }
};
`;

fs.writeFileSync(path.join(__dirname, "../src/assets/asset-manifest.ts"), manifestStr, "utf8");
console.log("Done!");
