// AUTOGENERATED ASSET MANIFEST
// Do not hardcode /media paths directly in components. Use this manifest.

export const assets = {
  home: {
    hero: {
      desktop: "/images/Home/Index%20Hero/home-hero-desktop-03.png",
      mobile: "/images/Home/Index%20Hero/home-hero-mobile-03.png",
    },
    editorial: [
      { id: 1, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-1.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-1.png" },
      { id: 2, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-2.png" },
      { id: 3, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-3.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-3.png" },
      { id: 4, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-4.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-4.png" },
      { id: 5, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-5.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-5.png" },
      { id: 6, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-6.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-6.png" },
      { id: 7, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-7.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-7.png" },
      { id: 8, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-8.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-8.png" },
      { id: 9, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-9.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-9.png" },
      { id: 10, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-10.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-10.png" },
      { id: 11, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-11.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-11.png" },
      { id: 12, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-12.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-12.png" },
      { id: 13, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-13.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-13.png" },
      { id: 14, desktop: "/images/Home/iconic%2014/Desktop/Index_iconic-14.png", mobile: "/images/Home/iconic%2014/Mobile/Index_iconic-14.png" },
    ],
  },

  about: {
    teamPhoto: "/media/images/about/team-photo.jpg",
    person: "/media/images/about/person.jpg",
  },

  crew: {
    group: "/media/images/crew/group.png",
    getMemberPhoto: (id: number) => `/media/images/crew/pic${id}.jpg`,
    getSpecialImage: (id: number) => `/media/images/crew/special-image-0${id}.jpg`,
  },

  recentWork: {
    recent01: "/media/images/recent-work/recent01.webp",
    recent01Jpg: "/media/images/recent-work/recent01.jpg",
    recent02: "/media/images/recent-work/recent02.webp",
    recent02Png: "/media/images/recent-work/recent02.png",
    recent03: "/media/images/recent-work/recent03.webp",
    recent03Jpg: "/media/images/recent-work/recent03.jpg",
  },

  misc: {
    favicon: "/media/images/misc/favicon-icon.png",
    parallaxBg: "/media/images/misc/parallax-bg.jpg",
    image4: "/media/images/misc/4.webp",
    image5: "/media/images/misc/5.webp",
    image6: "/media/images/misc/6.webp",
    dscf0463: "/media/images/misc/dscf0463-copy.webp",
    redTelephone: "/media/images/misc/red-rotary-telephone.jpg",
    speakerLogo: "/media/images/misc/logo.png",
  },

  videos: {
    hero: "/media/videos/hero/herovideo.mp4",
    showcase: "/media/videos/showcase/the-swayamvar-2.mp4",
    background: {
      wedding: "/media/videos/background/wedding.mp4",
      celebration: "/media/videos/background/celebration.mp4",
      portraits: "/media/videos/background/portraits.mp4",
      prewedding: "/media/videos/background/prewedding.mp4",
      rituals: "/media/videos/background/rituals.mp4",
      videoseen: "/media/videos/background/videoseen.mp4",
      ivorySeries: "/media/videos/background/ivory-series.mp4",
    },
    films: {
      film01: "/media/videos/films/film-01.mp4",
      film03: "/media/videos/films/film-03.mp4",
      film05: "/media/videos/films/film-05.mp4",
      film06: "/media/videos/films/film-06.mp4",
      film07: "/media/videos/films/film-07.mp4",
      film08: "/media/videos/films/film-08.mp4",
      film09: "/media/videos/films/film-09.mp4",
    },
  },

  svg: {
    logo: "/media/svg/logo/swamyvar-logo.svg",
  },

  audio: {
    music: {
      cinematicWedding: "/media/audio/music/cinematic-wedding.mp3",
    },
  },

  fonts: {
    orangeAvenue: "/media/fonts/orangeavenuedemo-regular.otf",
  },
};
