// AUTOGENERATED ASSET MANIFEST
// Do not hardcode /media paths directly in components. Use this manifest.

export const assets = {
  home: {
    hero: {
      desktop: "/media/images/home/hero/home_hero_03_desktop.webp",
      mobile: "/media/images/home/hero/home_hero_03_mobile.webp",
    },
    editorial: [
      { id: 1, desktop: "/media/images/home/editorial/home_editorial_01_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_01_mobile.webp" },
      { id: 2, desktop: "/media/images/home/editorial/home_editorial_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_02_mobile.webp" },
      { id: 3, desktop: "/media/images/home/editorial/home_editorial_03_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_03_mobile.webp" },
      { id: 4, desktop: "/media/images/home/editorial/home_editorial_04_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_04_mobile.webp" },
      { id: 5, desktop: "/media/images/home/editorial/home_editorial_05_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_05_mobile.webp" },
      { id: 6, desktop: "/media/images/home/editorial/home_editorial_06_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_06_mobile.webp" },
      { id: 7, desktop: "/media/images/home/editorial/home_editorial_07_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_07_mobile.webp" },
      { id: 8, desktop: "/media/images/home/editorial/home_editorial_08_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_08_mobile.webp" },
      { id: 9, desktop: "/media/images/home/editorial/home_editorial_09_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_09_mobile.webp" },
      { id: 10, desktop: "/media/images/home/editorial/home_editorial_10_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_10_mobile.webp" },
      { id: 11, desktop: "/media/images/home/editorial/home_editorial_11_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_11_mobile.webp" },
      { id: 12, desktop: "/media/images/home/editorial/home_editorial_12_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_12_mobile.webp" },
      { id: 13, desktop: "/media/images/home/editorial/home_editorial_13_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_13_mobile.webp" },
      { id: 14, desktop: "/media/images/home/editorial/home_editorial_14_desktop.webp", mobile: "/media/images/home/editorial/home_editorial_14_mobile.webp" },
    ],
  },

  about: {
    teamPhoto: "/media/images/about/team/about_team_alt1.webp",
    person: "/media/images/about/general/about_general_person_alt1.webp",
  },

  crew: {
    group: "/media/images/crew/group.png",
    getMemberPhoto: (id: number) => `/media/images/crew/pic${id}.jpg`,
    getSpecialImage: (id: number) => `/media/images/crew/special-image-0${id}.jpg`,
  },

  recentWork: {
    recent01: "/media/images/recent-work/general/recent-work_general_01_alt1.webp",
    recent01Jpg: "/media/images/recent-work/general/recent-work_general_01.webp",
    recent02: "/media/images/recent-work/general/recent-work_general_02_alt1.webp",
    recent02Png: "/media/images/recent-work/general/recent-work_general_02.webp",
    recent03: "/media/images/recent-work/general/recent-work_general_03_alt1.webp",
    recent03Jpg: "/media/images/recent-work/general/recent-work_general_03.webp",
  },

  misc: {
    favicon: "/media/images/misc/general/misc_general_favicon_alt1.webp",
    parallaxBg: "/media/images/misc/general/misc_general_parallax.webp",
    image4: "/media/images/misc/general/misc_general_04_alt1.webp",
    image5: "/media/images/misc/general/misc_general_05_alt1.webp",
    image6: "/media/images/misc/general/misc_general_06_alt1.webp",
    dscf0463: "/media/images/misc/general/misc_general_0463.webp",
    redTelephone: "/media/images/misc/red-rotary-telephone.jpg",
    speakerLogo: "/media/images/misc/logo.png",
  },

  videos: {
    hero: "/media/videos/hero/herovideo.mp4",
    showcase: "/media/videos/showcase/the-swayamvar-2.mp4",
    background: {
      wedding: "/media/videos/background/wedding.mp4",
      celebration: "/media/videos/background/celebration.mp4",
      portraits: "/media/videos/background/portraits.mp4",
      prewedding: "/media/videos/background/prewedding.mp4",
      rituals: "/media/videos/background/rituals.mp4",
      videoseen: "/media/videos/background/videoseen.mp4",
      ivorySeries: "/media/videos/background/ivory-series.mp4",
    },
    films: {
      film01: "/media/videos/films/film-01.mp4",
      film03: "/media/videos/films/film-03.mp4",
      film05: "/media/videos/films/film-05.mp4",
      film06: "/media/videos/films/film-06.mp4",
      film07: "/media/videos/films/film-07.mp4",
      film08: "/media/videos/films/film-08.mp4",
      film09: "/media/videos/films/film-09.mp4",
    },
  },

  svg: {
    logo: "/media/images/misc/general/misc_general_logo_alt1.svg",
  },

  audio: {
    music: {
      cinematicWedding: "/media/audio/music/cinematic-wedding.mp3",
    },
  },

  fonts: {
    orangeAvenue: "/media/fonts/orangeavenuedemo-regular.otf",
  },
};
