/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmRouteImport } from './routes/film'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PhotographyIndexRouteImport } from './routes/photography.index'
import { Route as PhotographySlugRouteImport } from './routes/photography.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyIndexRoute = PhotographyIndexRouteImport.update({
  id: '/photography/',
  path: '/photography/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographySlugRoute = PhotographySlugRouteImport.update({
  id: '/photography/$slug',
  path: '/photography/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/film': typeof FilmRoute
  '/services': typeof ServicesRoute
  '/photography/$slug': typeof PhotographySlugRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/film': typeof FilmRoute
  '/services': typeof ServicesRoute
  '/photography/$slug': typeof PhotographySlugRoute
  '/photography': typeof PhotographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/film': typeof FilmRoute
  '/services': typeof ServicesRoute
  '/photography/$slug': typeof PhotographySlugRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/film' | '/services' | '/photography/$slug' | '/photography/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/film' | '/services' | '/photography/$slug' | '/photography'
  id:
    | '__root__'
    | '/'
    | '/film'
    | '/services'
    | '/photography/$slug'
    | '/photography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmRoute: typeof FilmRoute
  ServicesRoute: typeof ServicesRoute
  PhotographySlugRoute: typeof PhotographySlugRoute
  PhotographyIndexRoute: typeof PhotographyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/': {
      id: '/photography/'
      path: '/photography'
      fullPath: '/photography/'
      preLoaderRoute: typeof PhotographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/$slug': {
      id: '/photography/$slug'
      path: '/photography/$slug'
      fullPath: '/photography/$slug'
      preLoaderRoute: typeof PhotographySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmRoute: FilmRoute,
  ServicesRoute: ServicesRoute,
  PhotographySlugRoute: PhotographySlugRoute,
  PhotographyIndexRoute: PhotographyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
