/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as FilmRouteImport } from './routes/film'
import { Route as LittleSnapRouteImport } from './routes/little-snap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VideographyRouteImport } from './routes/videography'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'
import { Route as PhotographyIndexRouteImport } from './routes/photography.index'
import { Route as PhotographySlugRouteImport } from './routes/photography.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const LittleSnapRoute = LittleSnapRouteImport.update({
  id: '/little-snap',
  path: '/little-snap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VideographyRoute = VideographyRouteImport.update({
  id: '/videography',
  path: '/videography',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyIndexRoute = PhotographyIndexRouteImport.update({
  id: '/photography/',
  path: '/photography/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographySlugRoute = PhotographySlugRouteImport.update({
  id: '/photography/$slug',
  path: '/photography/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crew': typeof CrewRoute
  '/film': typeof FilmRoute
  '/little-snap': typeof LittleSnapRoute
  '/services': typeof ServicesRoute
  '/videography': typeof VideographyRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/photography/$slug': typeof PhotographySlugRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crew': typeof CrewRoute
  '/film': typeof FilmRoute
  '/little-snap': typeof LittleSnapRoute
  '/services': typeof ServicesRoute
  '/videography': typeof VideographyRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/photography/$slug': typeof PhotographySlugRoute
  '/photography': typeof PhotographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crew': typeof CrewRoute
  '/film': typeof FilmRoute
  '/little-snap': typeof LittleSnapRoute
  '/services': typeof ServicesRoute
  '/videography': typeof VideographyRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/photography/$slug': typeof PhotographySlugRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/crew'
    | '/film'
    | '/little-snap'
    | '/services'
    | '/videography'
    | '/films/$slug'
    | '/photography/$slug'
    | '/photography/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/crew'
    | '/film'
    | '/little-snap'
    | '/services'
    | '/videography'
    | '/films/$slug'
    | '/photography/$slug'
    | '/photography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/crew'
    | '/film'
    | '/little-snap'
    | '/services'
    | '/videography'
    | '/films/$slug'
    | '/photography/$slug'
    | '/photography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CrewRoute: typeof CrewRoute
  FilmRoute: typeof FilmRoute
  LittleSnapRoute: typeof LittleSnapRoute
  ServicesRoute: typeof ServicesRoute
  VideographyRoute: typeof VideographyRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  PhotographySlugRoute: typeof PhotographySlugRoute
  PhotographyIndexRoute: typeof PhotographyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/little-snap': {
      id: '/little-snap'
      path: '/little-snap'
      fullPath: '/little-snap'
      preLoaderRoute: typeof LittleSnapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videography': {
      id: '/videography'
      path: '/videography'
      fullPath: '/videography'
      preLoaderRoute: typeof VideographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/': {
      id: '/photography/'
      path: '/photography'
      fullPath: '/photography/'
      preLoaderRoute: typeof PhotographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/$slug': {
      id: '/photography/$slug'
      path: '/photography/$slug'
      fullPath: '/photography/$slug'
      preLoaderRoute: typeof PhotographySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CrewRoute: CrewRoute,
  FilmRoute: FilmRoute,
  LittleSnapRoute: LittleSnapRoute,
  ServicesRoute: ServicesRoute,
  VideographyRoute: VideographyRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  PhotographySlugRoute: PhotographySlugRoute,
  PhotographyIndexRoute: PhotographyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
